# Generated by Django 5.0.6 on 2024-07-02 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_room_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='current_drawer',
            field=models.IntegerField(default=0),
        ),
    ]
