# Generated by Django 5.0.6 on 2024-07-02 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_room_current_drawer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='current_step',
        ),
        migrations.RemoveField(
            model_name='room',
            name='current_word',
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.room')),
            ],
        ),
    ]
